### PR TITLE
[SERV-767] Migrate to Google Analytics 4

### PR DESCRIPTION
**Pull request by markmatney**

### CODE REVIEW

**Review by ksclarke — DISMISSED** [review]
Looks good.

Side question -- did you get this running locally? I'm having local cert issues.

**Review by DRickard — DISMISSED** [review]

**Comment by markmatney** [comment]
`mvn clean package` is failing for me at Surefire:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_773e439.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:139)
	at org.jacoco.agent.rt.internal_773e439.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:100)
	at org.jacoco.agent.rt.internal_773e439.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_773e439.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:1999)
	at org.jacoco.agent.rt.internal_773e439.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:137)
	... 9 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
SUREFIRE-859: FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Aborted (core dumped)
```

```bash
$ mvn -version
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /opt/apache-maven-3.8.7
Java version: 11.0.18, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.19.0-35-generic", arch: "amd64", family: "unix"
```

**Comment by ksclarke** [comment]
I think it's fine to go ahead with this approval/merge. I'll work on the build issues in the ticket I'm working.

**Comment by markmatney** [comment]
Welp, turns out I forgot to add the body script to all the pages. Fixed now; thanks @ksclarke for prompting me to actually run locally.

After switching to Java 8, I am able to build the site and run it locally. @ksclarke if in Firefox you're seeing a page that says `Warning: Potential Security Risk Ahead`: from what I can remember, we've always seen this with local instances.

**Comment by ksclarke** [comment]
Yes, that warning was always there for local builds.

**Comment by markmatney** [comment]
You're seeing a different local cert issue?

**Comment by ksclarke** [comment]
I was but that's gone now. I get jacoco issues and a few module issues, but I'm updating the project to a newer JDK too (for security) so resolving those in the process.

**Review by ksclarke — APPROVED** [review]

**Review by DRickard — APPROVED** [review]

**Pull request merged**
